---
ansible_become: true
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3

# System configuration
timezone: UTC
system_locale: en_US.UTF-8

# Monitoring
monitoring_enabled: true
monitoring_prometheus_node_exporter: true

# User management
admin_users:
  - name: "{{ ansible_user }}"
    groups: "sudo"
    shell: /bin/bash
    ssh_keys: "{{ admin_ssh_keys | default([]) }}"
    state: present

# Applications management
applications:
  coolify:
    enabled: false
    state: latest
  dokploy:
    enabled: false
    state: latest
  tailscale:
    enabled: false
  borgbackup:
    enabled: false
