---
ntp_enabled: true
ntp_timezone: Etc/UTC
ntp_manage_config: true

ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
ntp_restrict:
  - "127.0.0.1"
  - "::1"

ntp_cron_handler_enabled: true
